application: prime31tasks
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /assets
  static_dir: assets



- url: .*
  script: main.py
